env:
 - MARATHONVERSION: 0.8.1
 - MARATHONVERSION: 0.8.2
 - MARATHONVERSION: 0.9.0

language: python
python:
  - 2.7
  - 3.4
sudo: true
install:
  - pip install tox
script:
  - ./itests/install-marathon.sh
  - /etc/init.d/zookeeper start
  - ./itests/start-marathon.sh &
  - make itests
